### ISSUE TITLE
关于论文表1实验

### ISSUE THREAD

**Issue by peakpang** [liuQuan98/APR#1]
你好，非常感谢你们出色的工作以及开源。想请问一下论文当中表一的实验结果
![image](https://github.com/liuQuan98/APR/assets/67569010/459eff55-a3fc-411f-8cc8-e295a4901fc2)
所选用的距离d1和d2是多少呢？

**Comment by liuQuan98** [comment]
Hi Peakpang,

We refer to the easiest vanilla KITTI and nuScenes as having d1=d2=10, which is exactly what we use to train and test the KITTI and nuScenes rows, in order to faithfully reproduce the 'close point clouds' in previous literature. On the other hand, LoKITTI and LoNuScenes are specially crafted datasets to contain only low overlap pairs (<=30%) for tests only, and the models we use here are first trained with d1=5, d2=20, then finetuned with d1=5, d2=30, and finally finetuned to d1=5, d2=50. A more aggresive strategy is also possible where you can skip the d2=30 step, which might work better for the KPConv series. I admit the finetuning process is a bit time consuming, and it might take you a few trials to get things working properly. Collapses are more frequent when dealing with distant pairs.

One more thing, if you are looking for a finetuning-free and better-performing distant point cloud registration method, do check out our latest work GCL (with a stunning +40% RR on KITTI[40,50]). In comparison, APR is completely overshadowed and therefore out of date.

Best,
Quan

**Comment by peakpang** [comment]
感谢感谢！
